name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: macos-latest # Use a macOS runner

    steps:
      - uses: actions/checkout@v4 # Checkout the repository code

      # - name: Set up Xcode
      #   run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build and Test
        run: |
          # Build the project and run tests with xcodebuild
          xcodebuild clean build test \
            -project BucketList.xcodeproj \
            -scheme BucketList \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6' \
            -enableCodeCoverage YES # Enable code coverage reporting

      - name: Check unit test results
        run: |
          # Check the test result and return failure if there are failing tests
          xcodebuild test -project BucketList.xcodeproj \
            -scheme BucketList \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6' | tee result.log | tail -n 20
          
          # Fail the job if there are any failed tests
          if grep -q "Test failed" result.log; then
            echo "Unit tests failed!"
            exit 1
          fi



